# Generated by Django 5.2 on 2025-05-20 22:28

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exlog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Zа-яА-ЯёЁ\\-\\s]*$', 'Только буквы, цифры, дефисы и пробелы разрешены.')]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_weight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='num_reps',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='num_sets',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
